"""Build data/life-tables.js from the UN World Population Prospects 2024.

Streams the complete (single year of age) life tables, medium variant, for
both sexes, females and males, keeps one calendar year, and writes remaining
life expectancy e(x) for ages 0 to 100 per country or area.

Usage: python3 scripts/build_life_tables.py [year]
"""
import csv
import gzip
import json
import sys
import urllib.request
from pathlib import Path

YEAR = sys.argv[1] if len(sys.argv) > 1 else "2026"
BASE = ("https://population.un.org/wpp/assets/Excel%20Files/"
        "1_Indicator%20(Standard)/CSV_FILES/")
FILES = {
    "b": "WPP2024_Life_Table_Complete_Medium_Both_2024-2100.csv.gz",
    "f": "WPP2024_Life_Table_Complete_Medium_Female_2024-2100.csv.gz",
    "m": "WPP2024_Life_Table_Complete_Medium_Male_2024-2100.csv.gz",
}
WORLD = "900"
COUNTRY = "4"
OUT = Path(__file__).resolve().parent.parent / "data" / "life-tables.js"


def rows(name):
    with urllib.request.urlopen(BASE + name) as resp:
        text = (line.decode("utf-8-sig") for line in gzip.GzipFile(fileobj=resp))
        header = next(csv.reader([next(text)]))
        key = f",{YEAR},"
        for line in text:
            if key in line:  # cheap prefilter; the csv parse below is exact
                yield dict(zip(header, next(csv.reader([line]))))


places = {}
for sex, name in FILES.items():
    print(f"reading {name}", file=sys.stderr)
    for r in rows(name):
        if r["Time"] != YEAR or not (r["LocTypeID"] == COUNTRY or r["LocID"] == WORLD):
            continue
        code = r["ISO3_code"] or "WLD"
        p = places.setdefault(code, {"n": r["Location"], "a2": r["ISO2_code"]})
        p.setdefault(sex, [None] * 101)[int(r["AgeGrpStart"])] = round(float(r["ex"]), 1)

complete = {k: v for k, v in places.items() if all(None not in v.get(s, [None]) for s in FILES)}
missing = sorted(set(places) - set(complete))
if missing:
    print(f"dropped incomplete: {missing}", file=sys.stderr)

payload = {"year": int(YEAR), "places": dict(sorted(complete.items()))}
OUT.write_text(
    "// Generated by scripts/build_life_tables.py. Do not edit by hand.\n"
    f"// Source: UN DESA, World Population Prospects 2024, complete life tables, medium variant, {YEAR}.\n"
    "// e(x) in years for ages 0 to 100; b = both sexes, f = female, m = male. License: CC BY 3.0 IGO.\n"
    "window.LIFE_TABLES = " + json.dumps(payload, separators=(",", ":"), ensure_ascii=False) + ";\n",
    encoding="utf-8",
)
print(f"wrote {len(complete)} places to {OUT}", file=sys.stderr)
